### ISSUE TITLE
Please update the link to the temporary license key.

### ISSUE THREAD

**Issue by adzuci** [turbonomic/lemur#13]
Hey there!

  I looked in https://github.com/turbonomic/lemur/wiki/Lemur-Installation#lemur-first-launch and tried to get to https://github.com/turbonomic/lemur/blob/master/Turbonomic-Engineering-Lemur-3M-100.xml but found a 404.  I'd also like to join the Slack, but wasn't able to use the https://joinlemur.herokuapp.com successfully.

  I'll try again later, but if there is an updated link that would be helpful!  Thanks in advance!

**Comment by enlinxu** [comment]
Thanks @adzuci for bringing this up! We are fixing it now.

**Comment by enlinxu** [comment]
@adzuci The license link was fixed already. We are using the heroku service for the slack invitation and it seems not working. Before we fix it, would you please use the manual signup link here: https://docs.google.com/forms/d/1N6BSlpDdsB5VT9FnEAC7SyTzAosPbhI_3ssdKVfAQ5U/viewform?edit_requested=true 

Thank you for your interest in Lemur, looking forward to speaking to you on slack.

**Comment by adzuci** [comment]
Thanks, not sure where I got the old link from, but https://github.com/turbonomic/lemur/blob/master/Turbonomic-Engineering-Lemur-6M-100.xml works & I dropped my email into the signup form.
